# Default relations for Social Stream
#
# Define the default relations and permissions offered by your application
# Though subjects (user, groups, etc.) can customize their own relations,
# these are the defaults to start up with
#
# Detailed information on permissions is available at:
# http://rdoc.info/gems/social_stream-base/Permission
#
user:
  friend:
    name: friend
    permissions:
      - [ follow ]
      - [ create,  activity ]
      - [ read,    activity ]
  acquaintance:
    name: acquaintance
    permissions:
      - [ read,    activity ]
  colleague:
    name: colleague
    permissions:
      - [ follow ]
      - [ create,  activity ]
      - [ read, activity ]

group:
  member:
    name: member
    permissions:
      - [ represent ]
      - [ create,  activity ]
      - [ read,    activity ]
      - [ read,    tie ]
  partner:
    name: partner
    permissions:
      - [ read,    activity ]
